Profiel pagina
PLA25/Website pull request #72
Opened 2018-06-04 13:51 UTC by ThomAat2

2018-06-04 14:23 UTC, mvegter requested changes

2018-06-04 14:23 UTC, mvegter commented on Source/controllers/account.controller.js
> +  const b = req.body;
Maak gebruik van [destructering](https://github.com/airbnb/javascript#destructuring).

2018-06-04 14:23 UTC, mvegter commented on Source/controllers/account.controller.js
> +      User.findOne({ email: req.user.email }).exec().then((user) => {
`.then((user) => {`
User kan null/undefined zijn, dus gooi hier een if statement na om dat te controlleren

2018-06-04 14:23 UTC, mvegter commented on Source/controllers/account.controller.js
> +      User.findOne({ email: req.user.email }).exec().then((user) => {
`.then((user) => {`
User kan null/undefined zijn, dus gooi hier een if statement na om dat te controlleren

2018-06-04 14:23 UTC, mvegter commented on Source/controllers/account.controller.js
> +    layout: 'layout-nonav',
Waarom wil je `nonav` gebruiken?

2018-06-04 14:23 UTC, mvegter commented on Source/controllers/index.js
> +router.use('/account', accountController);
sorteren op alfabet

2018-06-04 14:23 UTC, mvegter commented on Source/public/js/profile.js
> +$(window).on('load', () => {
We gebruiken voor alle js-bestanden:
`$(document).ready(() => {
...
});`

2018-06-04 14:23 UTC, mvegter commented on Source/views/profile.hbs
> +<!-- <div id="background"></div>
Oude code graag verwijderen

2018-06-04 14:23 UTC, mvegter commented on Source/views/profile.hbs
> +					Name
Niet vergeten de vertalingen erin te zetten

2018-06-05 17:48 UTC, Briadark requested changes

2018-06-05 17:48 UTC, Briadark commented on Source/views/editProfile.hbs
> +<!DOCTYPE html>
Niet in lijn met het ontwerp van de rest van het project. De knop is lichtpaars (maak deze blauw).

Het is eventueel mooier om bijde edit functies in 1 tabel te zetten (password en name)

2018-06-05 17:48 UTC, Briadark commented on Source/views/profile.hbs
> +<!-- Profiel Pagina -->
Niet in lijn met het ontwerp van de rest van het project. De knop is oranje (maak deze blauw) en de tekst staat los op de pagina i.p.v. netjes in een blok, zie als voorbeeld de admin pagina.

2018-06-05 18:17 UTC, Briadark requested changes

2018-06-05 18:17 UTC, Briadark commented on Source/views/profile.hbs
> +<button class="btn btn-primary">{{i18n "account.edit_profile"}}</button>
De knop werkt nu niet meer. Zie /js/profile.js

2018-06-05 18:18 UTC, Briadark commented on Source/views/editProfile.hbs
> +<!DOCTYPE html>
De knop is bij deze nog lichtpaars.

2018-06-05 18:19 UTC, Briadark commented on Source/views/profile.hbs
> +<button class="btn btn-primary">{{i18n "account.edit_profile"}}</button>
Zorg ook dat je de account informatie netjes in een tabel zet zoals bijvoorbeeld in je edit pagina of de admin pagina.
Niet de losse tekst op de pagina

2018-06-05 18:59 UTC, mvegter submitted a review, later dismissed
Back-end ziet er goed uit

2018-06-06 05:23 UTC, Briadark submitted a review, later dismissed

2018-06-06 12:40 UTC, mvegter approved these changes

2018-06-06 12:40 UTC, Briadark approved these changes

2018-06-06 12:41 UTC, merged