Knoppen voor het bewerken van de gebruikers
PLA25/Website pull request #74
Opened 2018-06-05 21:28 UTC by ThomAat2

2018-06-06 20:24 UTC, mvegter requested changes
Waar zijn de unit tests?

2018-06-06 20:24 UTC, mvegter commented on Source/controllers/admin.controller.js
> +    User.deleteOne({
We gebruiken promises

2018-06-06 20:24 UTC, mvegter commented on Source/controllers/admin.controller.js
> +    if (!user) {
Hier is een user niet gevonden

2018-06-06 20:24 UTC, mvegter commented on Source/controllers/admin.controller.js
> +    next(new Error(`Could not find user "${req.params.email}"`));
Dit is een 'unhandled' exception/error, niet een key not found

2018-06-06 20:24 UTC, mvegter commented on Source/controllers/admin.controller.js
> +    next(new Error(`Could not find user "${req.params.email}"\nMessage: ${e.message}`));
Dit is niet een user not found

2018-06-06 20:24 UTC, mvegter commented on Source/public/js/admin.js
> +// eslint-disable-next-line no-unused-vars
?

2018-06-06 20:24 UTC, mvegter commented on Source/public/js/admin.js
> +  window.location.href = `/admin/editUser/${email}`;
Waarom geen `<a>`

2018-06-06 20:24 UTC, mvegter commented on Source/public/js/profile.js
> +  const knop = $('button.btn#edit-button');
gebruik alleen id's

2018-06-06 20:24 UTC, mvegter commented on Source/views/editUser.hbs
> +</div>
indent?

2018-06-06 20:24 UTC, mvegter commented on Source/views/editUser.hbs
> +		overflow: hidden;
dit betekent waarschijnlijk dat je ergens te vroeg/laat een div hebt afgesloten

2018-06-06 20:24 UTC, mvegter commented on Source/views/editUser.hbs
> +		width: 450px;
responsive?

2018-06-08 15:10 UTC, ThomAat2 commented on Source/public/js/admin.js
> +// eslint-disable-next-line no-unused-vars
Deze functie wordt aangeroepen vanuit de html pagina en staat gedeclareerd in het js bestand. Dat herkent hij niet.

2018-06-08 15:53 UTC, ThomAat2 commented on Source/views/editUser.hbs
> +		overflow: hidden;
Als ik dat weghaal en de "div.row" een breedte van 100% geef, dan krijg ik extra ruimte aan de rechter kant. Geen idee hoe het komt, de structuur klopt.

2018-06-17 07:47 UTC, closed without merging